// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package rider

import (
	"go.mongodb.org/mongo-driver/mongo"
	"rideShare/internal/rider"
	"rideShare/internal/rider/service"
)

// Injectors from wire.go:

func RiderControllerWire(client *mongo.Database) (*Controller, error) {
	repository := rider.NewRepository(client)
	service := riderService.NewService(repository)
	controller := NewController(service)
	return controller, nil
}
