// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ride

import (
	"go.mongodb.org/mongo-driver/mongo"
	"rideShare/internal/driver"
	"rideShare/internal/driver/service"
	"rideShare/internal/ride"
	"rideShare/internal/ride/service"
	"rideShare/internal/rider"
)

// Injectors from wire.go:

func RideControllerWire(client *mongo.Database) (*Controller, error) {
	repository := ride.NewRepository(client)
	driverRepository := driver.NewRepository(client)
	service := driverService.NewService(driverRepository)
	riderRepository := rider.NewRepository(client)
	rideServiceService := rideService.NewService(repository, service, driverRepository, riderRepository)
	controller := NewController(rideServiceService)
	return controller, nil
}
