// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package driver

import (
	"go.mongodb.org/mongo-driver/mongo"
	"rideShare/internal/driver"
	"rideShare/internal/driver/service"
)

// Injectors from wire.go:

func DriverControllerWire(client *mongo.Database) (*Controller, error) {
	repository := driver.NewRepository(client)
	service := driverService.NewService(repository)
	controller := NewController(service)
	return controller, nil
}
